project_id = "xfuehhrpdzkdsjhfbjcd"

[functions.import-fact-daily]
verify_jwt = false

[functions.import-locations]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.import-sales]
verify_jwt = true

[functions.import-inventory]
verify_jwt = true

[functions.archie-chat]
verify_jwt = true

[functions.dbm-calculator]
verify_jwt = false

[functions.notion-sync-knowledge]
verify_jwt = true

[functions.prepare-dataset]
verify_jwt = false
